# Generated by Django 3.1.7 on 2021-03-24 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_platform', '0002_auto_20210323_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default=' ', max_length=100, verbose_name='Desc'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(related_name='watchlists', to='trade_platform.Item'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='trade_platform.profile'),
        ),
    ]
