# Generated by Django 3.1.7 on 2021-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_platform', '0003_auto_20210324_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default=' ', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, default=5000, max_digits=20, null=True),
        ),
    ]
