# Generated by Django 3.1.7 on 2021-05-18 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_platform', '0005_auto_20210516_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShiftPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('startdate', models.DateField(default=datetime.date(2021, 5, 18))),
                ('enddate', models.DateField(default=datetime.date(2021, 5, 18))),
            ],
        ),
        migrations.AddField(
            model_name='workshift',
            name='workshit_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshifts', to='trade_platform.workshiftplan'),
        ),
    ]
