# Generated by Django 3.1.7 on 2021-05-18 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_platform', '0006_auto_20210518_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 8, 7, 30, 816526)),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 8, 7, 30, 816499)),
        ),
    ]
