# Generated by Django 3.1.7 on 2021-05-19 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_platform', '0007_auto_20210518_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('factor', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='contract_end_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 19, 8, 34, 18, 66335)),
        ),
        migrations.AddField(
            model_name='position',
            name='contract_start_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 19, 8, 34, 18, 66305)),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 8, 34, 18, 65581)),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 8, 34, 18, 65554)),
        ),
        migrations.AlterField(
            model_name='workshiftplan',
            name='enddate',
            field=models.DateField(default=datetime.date(2021, 5, 19)),
        ),
        migrations.AlterField(
            model_name='workshiftplan',
            name='startdate',
            field=models.DateField(default=datetime.date(2021, 5, 19)),
        ),
        migrations.AddField(
            model_name='position',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='trade_platform.location'),
        ),
    ]
