# Generated by Django 3.1.7 on 2021-05-19 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_platform', '0009_auto_20210519_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='contract_end_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 19, 12, 36, 57, 828187)),
        ),
        migrations.AlterField(
            model_name='position',
            name='contract_start_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 19, 12, 36, 57, 828165)),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 12, 36, 57, 827405)),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 12, 36, 57, 827356)),
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('ch', 'Chinese')], default='en', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
