# Generated by Django 3.1.7 on 2021-05-20 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trade_platform', '0014_auto_20210520_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='contract_end_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 20, 8, 25, 3, 270686)),
        ),
        migrations.AlterField(
            model_name='position',
            name='contract_start_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 20, 8, 25, 3, 270673)),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 8, 25, 3, 270230)),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 8, 25, 3, 270206, tzinfo=utc)),
        ),
    ]
