version: "3.9"

services:
  redis:
    image: redis:latest
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/13/main
    env_file:
      - ./.env.dev
  web:
    build: .
    command: gunicorn stock_platform.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  celery:
    restart: always
    build:
      context: .
    command: celery -A stock_platform worker -B -E -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - web

volumes:
  static_volume: